package com.bignerdranch.android.geoquiz;

/**
 * Created by rana_ on 11/30/2016.
 */

public class Question {

    /* We have these a m<VariableName> to allow for autogeneration which is done in the settings */
    private int mTextResId;
    private boolean mAnswerTrue;

    public Question(int textResId, boolean answerTrue){
        mTextResId = textResId;
        mAnswerTrue = answerTrue;
    }


    /*
    Autogenerated getters/setters.
     */
    public int getTextResId() {
        return mTextResId;
    }

    public void setTextResId(int textResId) {
        mTextResId = textResId;
    }

    public boolean isAnswerTrue() {
        return mAnswerTrue;
    }

    public void setAnswerTrue(boolean answerTrue) {
        mAnswerTrue = answerTrue;
    }
}
